=== GossJS/15092017-Arifmed24/part3/3.dtd
<?xml version="1.0" encoding="utf-8" ?>
        <!ELEMENT statistics (visits,ips)>
        <!ELEMENT visits (stationary, mobile)>
        <!ELEMENT stationary (platform*)>
        <!ELEMENT mobile (platform*)>
        <!ELEMENT platform (#PCDATA)>
        <!ATTLIST platform name CDATA #REQUIRED>
        <!ELEMENT ips (ip+)>
        <!ELEMENT ip EMPTY>
        <!ATTLIST ip addr CDATA #REQUIRED>
        <!ATTLIST ip frequency CDATA #REQUIRED>

=== GossJS/15092017-Arifmed24/part3/3.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE statistics PUBLIC "Arif" "3.dtd">
<statistics>
    <visits>
        <stationary>
            <platform name="Windows">87</platform>
            <platform name="Linux">8</platform>
            <platform name="Mac OS">6</platform>
        </stationary>
        <mobile>
            <platform name="iOS">11</platform>
            <platform name="Android">5</platform>
        </mobile>
    </visits>
    <ips>
        <ip addr="077.234.203.101" frequency="12"/>
        <ip addr="005.144.096.251" frequency="11"/>
        <ip addr="081.222.086.058" frequency="6"/>
        <ip addr="094.019.018.060" frequency="4"/>
        <ip addr="005.164.066.173" frequency="4"/>
    </ips>
</statistics>
